import {
  AppWindow,
  Bell,
  BookOpen,
  Calendar,
  ChartColumn,
  Check,
  Clock,
  Code,
  Compass,
  Database,
  Eye,
  FileText,
  Flag,
  Folder,
  Gauge,
  Inbox,
  KeyRound,
  LayoutTemplate,
  Lock,
  MessagesSquare,
  PenTool,
  Plug,
  Receipt,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Target,
  User,
  Workflow,
  Zap,
  type LucideProps,
} from "lucide-react";

const icons = {
  app: AppWindow,
  bell: Bell,
  book: BookOpen,
  calendar: Calendar,
  chart: ChartColumn,
  chat: MessagesSquare,
  check: Check,
  clock: Clock,
  code: Code,
  compass: Compass,
  database: Database,
  eye: Eye,
  file: FileText,
  flag: Flag,
  folder: Folder,
  gauge: Gauge,
  inbox: Inbox,
  key: KeyRound,
  layout: LayoutTemplate,
  lock: Lock,
  pen: PenTool,
  plug: Plug,
  receipt: Receipt,
  rocket: Rocket,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  user: User,
  workflow: Workflow,
  zap: Zap,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.6} {...props} />;
}
